---
name: Deploy
on:  
  push:
    branches: [main, devops/test-deploy-main, develop, devops/test-deploy-dev]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: >
      ${{ github.ref_name == 'main' ||
          github.ref_name == 'devops/test-deploy-main'
      && 'production' || 'dev' }}
    env:
      CI_VITE_API_DOMAIN: ${{ vars.CI_VITE_API_DOMAIN }}
    steps:
      - name: 1. Check out branch
        uses: actions/checkout@v3

      - name: 2. Create .env file for CI
        run: |
          pip3 install dump-env
          dump-env \
            -t .env.template \
            -p 'CI_' > .env

      - name: 3. Install npm
        run: |
          sudo apt install nodejs npm -y
          npm ci 

      - name: 4. Build dist folder
        run: |
          npm run build

      - name: Copy dist to dev folder on server
        if:  ${{ github.ref_name != 'main' && github.ref_name != 'devops/test-deploy-main' }}
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          overwrite: true
          source: 'dist'
          target: '~/frontend/dev/'

      - name: Copy dist to prod folder on server
        if: ${{ github.ref_name == 'main' || github.ref_name == 'devops/test-deploy-main' }}
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          overwrite: true
          source: 'dist'
          target: '~/frontend/prod/'
