---
name: Test deploy
on:  
  push:
    branches: [develop, devops/test-deploy-dev]

#  env:
#    API_URL: 'https://teamclimate.rassokha.pro:8000/api'

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check out branch
        uses: actions/checkout@v3

      - name: 2. Create .env file for CI
        run: |
          pip3 install dump-env
          dump-env \
            -t .env.template \
            -p 'CI_' > .env

      - name: 3. Build docker-image with npm build
        run: |
          docker build --target build -t teamclimate-frontend:dev .
  ssh-commands:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - uses: actions/checkout@v3
        name: Check out branch

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          overwrite: true
          source: 'devops'
          target: '~/github_workflow_frontend'

      - name: docker-compose up frontend
        uses: appleboy/ssh-action@v1
        env:
          VERSION: ${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}

        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          envs: VERSION,GITHUB_ACTOR,GITHUB_REF_NAME,GITHUB_COMMIT_SHA
          script: |
            env
            cp ~/github_workflow_frontend/devops/nginx.frontend-dev.conf /mnt/docker_data/nginx/conf/conf.d/
            cp github_workflow_frontend/devops/docker-compose-frontend.yaml ~/
            docker compose -f docker-compose-frontend.yaml up -d frontend-dev
            docker restart nginx
